[package]
name = "lily-lexer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.63"
unicode_categories = "0.1.1"

[dev-dependencies]
insta = "1.19.1"
pretty_assertions = "1.3.0"
