[package]
name = "lily-cst"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.3"
pest = "2.1.3"
pest_derive = "2.1.0"
