[package]
name = "lily-cst"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fancy-regex = "0.10.0"
lalrpop-util = "0.19.8"
lily-interner = { version = "0.0.0", path = "../lily-interner" }

[build-dependencies]
lalrpop = "0.19.8"
